# Generated by Django 3.2.12 on 2022-11-18 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'verbose_name': 'exercise', 'verbose_name_plural': 'exercises'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'group', 'verbose_name_plural': 'groups'},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': 'media', 'verbose_name_plural': 'media'},
        ),
    ]
