# Generated by Django 3.2.12 on 2022-11-18 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_base', '0002_auto_20221118_2301'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'verbose_name': 'goal', 'verbose_name_plural': 'goals'},
        ),
        migrations.AlterModelOptions(
            name='workoutday',
            options={'verbose_name': 'workout day', 'verbose_name_plural': 'workout days'},
        ),
        migrations.AlterField(
            model_name='goal',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='exercise_base.exercise'),
        ),
    ]
