# Generated by Django 3.2.12 on 2022-11-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_auto_20221118_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='sets_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
